# Generated by Django 3.0.8 on 2020-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
