# Generated by Django 3.0.8 on 2020-07-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclist', '0002_auto_20200714_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
